// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package client

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	EditorAuthScopes = "editorAuth.Scopes"
	RootAuthScopes   = "rootAuth.Scopes"
)

// AutoDJConfig defines model for AutoDJConfig.
type AutoDJConfig struct {
	Stub *struct {
		MediaID   *int `json:"MediaID,omitempty"`
		Threshold *int `json:"Threshold,omitempty"`
	} `json:"Stub,omitempty"`
	Tags *TagList `json:"Tags,omitempty"`
}

// LoginForm defines model for LoginForm.
type LoginForm struct {
	Login string `json:"login"`
	Pass  string `json:"pass"`
}

// Media defines model for Media.
type Media struct {
	Author   *string `json:"author,omitempty"`
	Duration *int    `json:"duration,omitempty"`
	Id       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// MediaArray defines model for MediaArray.
type MediaArray = []Media

// MediaRegister defines model for MediaRegister.
type MediaRegister struct {
	Author *string  `json:"author,omitempty"`
	Id     *int     `json:"id,omitempty"`
	Name   *string  `json:"name,omitempty"`
	Tags   *TagList `json:"tags,omitempty"`
}

// Segment defines model for Segment.
type Segment struct {
	// BeginCut time cut in ns
	BeginCut *int `json:"beginCut,omitempty"`
	Id       *int `json:"id,omitempty"`

	// MediaID ID of corresponding media
	MediaID *int `json:"mediaID,omitempty"`

	// Start Unix time
	Start *int `json:"start,omitempty"`

	// StopCut time cut in ns
	StopCut *int `json:"stopCut,omitempty"`
}

// SegmentRegister defines model for SegmentRegister.
type SegmentRegister struct {
	// BeginCut time cut in ns
	BeginCut *int `json:"beginCut,omitempty"`

	// MediaID ID of corresponding media
	MediaID *int `json:"mediaID,omitempty"`

	// Start Unix time
	Start *int `json:"start,omitempty"`

	// StopCut time cut in ns
	StopCut *int `json:"stopCut,omitempty"`
}

// Segments defines model for Segments.
type Segments = []Segment

// Tag defines model for Tag.
type Tag struct {
	Id   *int     `json:"id,omitempty"`
	Type *TagType `json:"type,omitempty"`
}

// TagList defines model for TagList.
type TagList = []Tag

// TagType defines model for TagType.
type TagType struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// TagTypes defines model for TagTypes.
type TagTypes = []TagType

// ID defines model for ID.
type ID = int64

// TimestampFrom defines model for timestampFrom.
type TimestampFrom = int64

// GetAdminLibraryMediaParams defines parameters for GetAdminLibraryMedia.
type GetAdminLibraryMediaParams struct {
	Name   *string   `form:"name,omitempty" json:"name,omitempty"`
	Author *string   `form:"author,omitempty" json:"author,omitempty"`
	Tags   *[]string `form:"tags,omitempty" json:"tags,omitempty"`
}

// PostAdminLibraryMediaMultipartBody defines parameters for PostAdminLibraryMedia.
type PostAdminLibraryMediaMultipartBody struct {
	Media  *MediaRegister      `json:"media,omitempty"`
	Source *openapi_types.File `json:"source,omitempty"`
}

// DeleteAdminScheduleParams defines parameters for DeleteAdminSchedule.
type DeleteAdminScheduleParams struct {
	// From UNIX timestamp
	From TimestampFrom `form:"from" json:"from"`
}

// GetAdminScheduleParams defines parameters for GetAdminSchedule.
type GetAdminScheduleParams struct {
	// Start start cut
	Start *int `form:"start,omitempty" json:"start,omitempty"`

	// Stop stop cut
	Stop *int `form:"stop,omitempty" json:"stop,omitempty"`
}

// PostAdminTagMultiIdJSONBody defines parameters for PostAdminTagMultiId.
type PostAdminTagMultiIdJSONBody struct {
	Ids *[]int `json:"ids,omitempty"`
}

// PostAdminLibraryMediaMultipartRequestBody defines body for PostAdminLibraryMedia for multipart/form-data ContentType.
type PostAdminLibraryMediaMultipartRequestBody PostAdminLibraryMediaMultipartBody

// PutAdminLibraryMediaJSONRequestBody defines body for PutAdminLibraryMedia for application/json ContentType.
type PutAdminLibraryMediaJSONRequestBody = MediaRegister

// PostAdminLibraryTagJSONRequestBody defines body for PostAdminLibraryTag for application/json ContentType.
type PostAdminLibraryTagJSONRequestBody = Tag

// PostAdminLoginJSONRequestBody defines body for PostAdminLogin for application/json ContentType.
type PostAdminLoginJSONRequestBody = LoginForm

// PostAdminScheduleJSONRequestBody defines body for PostAdminSchedule for application/json ContentType.
type PostAdminScheduleJSONRequestBody = SegmentRegister

// PostAdminScheduleDjConfigJSONRequestBody defines body for PostAdminScheduleDjConfig for application/json ContentType.
type PostAdminScheduleDjConfigJSONRequestBody = AutoDJConfig

// PostAdminTagMultiIdJSONRequestBody defines body for PostAdminTagMultiId for application/json ContentType.
type PostAdminTagMultiIdJSONRequestBody PostAdminTagMultiIdJSONBody
