# coding: utf-8

"""
    Phystech Radio - OpenAPI 3.0

    This is a Phystech Radio specification.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LibraryMediaBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'media': 'MediaRegister',
        'source': 'str'
    }

    attribute_map = {
        'media': 'media',
        'source': 'source'
    }

    def __init__(self, media=None, source=None):  # noqa: E501
        """LibraryMediaBody - a model defined in Swagger"""  # noqa: E501
        self._media = None
        self._source = None
        self.discriminator = None
        if media is not None:
            self.media = media
        if source is not None:
            self.source = source

    @property
    def media(self):
        """Gets the media of this LibraryMediaBody.  # noqa: E501


        :return: The media of this LibraryMediaBody.  # noqa: E501
        :rtype: MediaRegister
        """
        return self._media

    @media.setter
    def media(self, media):
        """Sets the media of this LibraryMediaBody.


        :param media: The media of this LibraryMediaBody.  # noqa: E501
        :type: MediaRegister
        """

        self._media = media

    @property
    def source(self):
        """Gets the source of this LibraryMediaBody.  # noqa: E501


        :return: The source of this LibraryMediaBody.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this LibraryMediaBody.


        :param source: The source of this LibraryMediaBody.  # noqa: E501
        :type: str
        """

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LibraryMediaBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LibraryMediaBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
